:llms:
  :request_timeout: 40
  :max_retries: 1
  :connectors:
    :gpt:       connect_gpt
    :gemini:    connect_gemini
    :mistralai: connect_morpheus
    :gemma:     connect_morpheus
    :qwen:      connect_morpheus
    :Qwen:      connect_morpheus

