#!/usr/bin/ruby
#
# This file is part of CPEE-LLM.
#
# CPEE-LLM is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# CPEE-LLM is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with CPEE-LLM (file LICENSE in the main directory). If not, see
# <http://www.gnu.org/licenses/>.

if File.exist?(File.join(__dir__,'..','lib','cpee','llm','implementation.rb'))
  require_relative File.join(__dir__,'..','lib','cpee','llm','implementation')
elsif File.exist?(File.join(Dir.home,'Projects','cpee-llm','lib','cpee','llm','implementation.rb'))
  require_relative File.join(Dir.home, 'Projects','cpee-llm','lib','cpee','llm','implementation')
else
  require 'cpee/llm/implementation'
end

options = {
  :host => 'localhost',
  :port => 9297,
  :secure => false,
  :llms => {}
}

Riddl::Server.new(CPEE::LLM::SERVER, options) do
  accessible_description true
  cross_site_xhr true

  @riddl_opts[:llms][:connectors].each do |k,v|
    @riddl_opts[:llms][:connectors][k] = File.read(v)
  end

  use CPEE::LLM::implementation(@riddl_opts)
end.loop!
