flowchart LR
se:startevent:((startevent))-->a1:script:(Initialize Loop Counter)
a1:script:(Initialize Loop Counter)-->a3:script:(Set Loop Counter to 0)
a3:script:(Set Loop Counter to 0)-->e1s:exclusivegateway:{x}
e1s:exclusivegateway:{x}-->|"data.loop_counter < 5"|e1e:exclusivegateway:{x}
e1e:exclusivegateway:{x}-->a7:task:(Measure Lighting Conditions)
a7:task:(Measure Lighting Conditions)-->e2s:exclusivegateway:{x}
e2s:exclusivegateway:{x}-->|"data.ambient_light_lux < 100"|a13:task:(Increase Brightness)
a13:task:(Increase Brightness)-->e2e:exclusivegateway:{x}
e2s:exclusivegateway:{x}-->|"data.ambient_light_lux > 800"|a15:task:(Reduce Brightness)
a15:task:(Reduce Brightness)-->e2e:exclusivegateway:{x}
e2s:exclusivegateway:{x}-->|"data.ambient_light_lux <= 10"|a17:task:(Turn Lights Off)
a17:task:(Turn Lights Off)-->e2e:exclusivegateway:{x}
e2e:exclusivegateway:{x}-->a19:task:(Wait 2 Seconds)
a19:task:(Wait 2 Seconds)-->a25:script:(Increment Loop Counter)
a25:script:(Increment Loop Counter)-->a27:script:(Update Loop Counter)
a27:script:(Update Loop Counter)-->e1s:exclusivegateway:{x}
e1e:exclusivegateway:{x}-->a9:task:(Switch Light Off)
a9:task:(Switch Light Off)-->ee:endevent:((endevent))