#!/usr/bin/ruby
#
# This file is part of CPEE-LLM.
#
# CPEE-LLM is free software: you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# CPEE-LLM is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with CPEE-LLM (file LICENSE in the main directory). If not, see
# <http://www.gnu.org/licenses/>.

require 'riddl/client'
require 'json'
require 'typhoeus'

# ./cpee-llm-tool.rb [new|adapt] [user_input] [instance_id] [llm] - last one (i.e., 'llm' is optional and default to 'geminin-2.5-flash-lite')

# e.g.,
# ./cpee-llm-tool.rb new 'The MPON sends the dismissal to the MPOO. The MPOO reviews the dismissal. The MPOO opposes the dismissal of MPON or the MPOO confirms the dismissal of the MPON.' 'geminin-2.0-flash' 1501
# ./cpee-llm-tool.rb adapt 'Add task A after dismissal review.' 'geminin-2.0-flash' 1501


srv = Riddl::Client.new('http://localhost:9297/')
status, res = srv.post [
  Riddl::Parameter::Complex.new("rpst_xml","text/xml",ARGV[0] == 'adapt' ? Typhoeus.get("https://cpee.org/flow/engine/#{ARGV[2]}/properties/dslx/").response_body() : File.read('cpee_empty_example')),
  Riddl::Parameter::Complex.new("user_input","text/plain",ARGV[1]),
  Riddl::Parameter::Complex.new("llm","text/plain",ARGV[3].nil?() ? 'gemini-2.5-flash-light' : ARGV[3])
]
if status >= 200 && status < 300
  res
else
  raise "llm did not work"
end
description = JSON.parse(res[0].value().read())['output_cpee']

srv = Riddl::Client.new("https://cpee.org/flow/engine/#{ARGV[2]}/properties/dslx/")
status, res = srv.put [
  Riddl::Parameter::Complex.new("dslx","text/xml",description)
]
if status >= 200 && status < 300
  res
end
